title: automation@sobolewska
description: automation@sobolewska
email: postmaster@sobolewska.it

url: sobolewska.it
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: sobolewska
   facebook: milrom
   email: milena@sobolewska.it
   
google_analytics: "UA-63723508-1"